### ISSUE TITLE
Missing utility classes (width) ?

### ISSUE THREAD

**Issue by alexparker** [chrism/emberjs-tailwind-purgecss#11]
I grabbed adams ui mock up example and dropped it in to see if it rendered the same with this ember setup guide, but seems that at least the `.w-9` class is missing.

**Comment by alexparker** [comment]
I also tried cloning your repo and adding the markup directly to it (this interface markup: https://www.youtube.com/watch?v=6xgMkGMIudE) and it had the same problem. Seems the `.w-9` class and other width or utility classes potentially are not being imported?

**Comment by chrism** [comment]
Sorry for the really slow reply.

I just took a look and it doesn’t seem like `.w-9` is included as a default class?

https://tailwindcss.com/docs/width/#app

```
.w-8 | width: 2rem;
.w-10 | width: 2.5rem;
```

Perhaps that was the issue?
