### ISSUE TITLE
Add this example to Tailwind's examples repo

### ISSUE THREAD

**Issue by steveszc** [chrism/emberjs-tailwind-purgecss#14]
The Tailwind CSS project maintains an examples repo https://github.com/tailwindcss/setup-examples

Its currently missing an example setup for Ember. Would be great to get this added there.

**Comment by chrism** [comment]
Thanks for the suggestion and I agree.

I need to implement this fix first though I think to remove the security warning.
https://github.com/ember-cli/ember-cli-preprocess-registry/issues/50#issuecomment-573946313

**Comment by MichalBryxi** [comment]
The repo mentioned in the ticket description says: "This repository has been archived by the owner. It is now read-only."

**Comment by chrism** [comment]
Thanks for the update.
