### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by jrock2004** [chrism/emberjs-tailwind-purgecss#2]
I am on Ember version 3.4 and when I try to run my server its complains about the spread operator `...`

<img width="766" alt="image" src="https://user-images.githubusercontent.com/655716/63795833-c5e02800-c8d2-11e9-87b3-d9207896d016.png">

**Comment by chrism** [comment]
Did you ever manage to resolve this issue @jrock2004 ?

**Comment by jrock2004** [comment]
If I remember right, I upgraded ember to newer version to fix this

**Comment by chrism** [comment]
Great, thanks so much for getting back to me.

I’m going to close this now then.
