### ISSUE TITLE
Failed to find 'tailwindcss/base' error

### ISSUE THREAD

**Issue by dgavey** [chrism/emberjs-tailwind-purgecss#4]
I'm using Ember 3.12 and following these instructions on build I got a 
`Failed to find 'tailwindcss/base'` message in the console.

I did some digging around and for a fix for this.  I needed to modify the ember-cli-build.js slightly.

Instead of the line `require('postcss-import')`

I had to add this.

```
{
  module: require('postcss-import'),
  options: {
    path: ['node_modules']
  }
},
```

Posting this to help others.  Wondering though if you need me to make a PR to update the readme?  I'm also not sure at this point if this change to the ember-cli-build.js would work for all versions of Ember or not.

**Comment by rwwagner90** [comment]
@chrism I can confirm that this fixes the issue. Should we update the instructions?

**Comment by chrism** [comment]
@dgavey @rwwagner90

Sorry I missed your first message on this—thanks for the information.

I’m going to update the docs today & will close this once it’s done.

Thank you!

**Comment by chrism** [comment]
@dgavey @rwwagner90 

Thanks again, I've just updated the build file and readme and it still seems to work fine with 3.9

I'm going to also update the repo itself to 3.13 when I have some time as it is a bit out of date now.

**Comment by MichalBryxi** [comment]
I'm using emberjs+tailwind using this setup together with [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/) and I got the same error described in this issue. The solution described in the ticket does not help me on it's own, I have to add following `nohoist` directives to to the base project `package.json`:

```json
{
  "name": "monorepo",
  "private": true,
  "workspaces": {
    "packages": [
      "frontend",
      "common-components"
    ],
    "nohoist": [
      "**/postcss-purgecss",
      "**/tailwindcss"
    ]
  },
}
```

Hope this might help someone.

**Comment by chrism** [comment]
Thanks for the heads up!

I haven’t been using Yarn workspaces yet personally.
